apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cheese-ingress
spec:
  tls:
  - hosts:
    - mysql.services.com
    secretName: my-secret
  rules:
  - host: mysql.services.com
    http:
      paths:
      - path: /url
        pathType: Prefix
        backend:
          service:
            name: nginx-secret-svc-url
            port:
              number: 80
      paths:
      - path: /username
        pathType: Prefix
        backend:
          service:
            name: nginx-secret-svc-username
            port:
              number: 80
      paths:
      - path: /password
        pathType: Prefix
        backend:
          service:
            name: nginx-secret-svc-password
            port:
              number: 80