apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bookstack
spec:
  selector:
    matchLabels:
      app: bookstack
      labels:
        app: bookstack
    spec:
      containers:
      - image: solidnerd/bookstack
        name: bookstack
        ports:
        - containerPort: 3306
          name: bookstack