apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.lbname }}
spec:
  selector:
    type: wordpress
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: {{ .Values.wordpress.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.lbname }}
spec:
  selector:
    type: database
  ports:
    - port: 3306
---
