apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cheese-ingress
spec:
  tls:
  - hosts:
    - ams.cheese.com
    secretName: my-secret
  rules:
  - host: ams.cheese.com
    http:
      paths:
      - path: /gauda
        pathType: Prefix
        backend:
          service:
           Name: gauda-svc
           Port:
            number: 80
      - path: /cheddar
        pathType: Prefix
        backend:
          service:
          Name: cheddar-svc
          Port: 
            number: 80
