apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  labels:
    app: nginx-secret
spec:
  containers:
    - name: nginx-secret
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
      - name: secret
        mountPath: "/usr/share/nginx/html"
        readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: mygninx-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: mygninx-secret
type: Opaque
data:
  username: cm9vdF91c2VyCg==
  password: RXhwZXJ0cyExMjMK
  db_url: bXlzcWwuc2VydmljZXMuY29tCg== 